apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
type: Opaque
data:
  # This value needs to be replaced with your base64-encoded YouTube API key
  # You can generate it with: echo -n "your-youtube-api-key" | base64
  YOUTUBE_API_KEY: __YOUTUBE_API_KEY__