apiVersion: v1
kind: Secret
metadata:
  name: auth0-secret
type: Opaque
data:
  # These values need to be replaced with actual base64-encoded Auth0 credentials
  # You can generate them with: echo -n "your-actual-value" | base64
  AUTH0_DOMAIN: __AUTH0_DOMAIN__
  AUTH0_CLIENT_ID: __AUTH0_CLIENT_ID__
  AUTH0_CLIENT_SECRET: __AUTH0_CLIENT_SECRET__
  AUTH0_CALLBACK_URL: __AUTH0_CALLBACK_URL__
  AUTH0_AUDIENCE: __AUTH0_AUDIENCE__
  SESSION_KEY: __AUTH0_SECRET__