apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-copilot-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-copilot-webapi
  template:
    metadata:
      labels:
        app: chat-copilot-webapi
    spec:
      containers:
      - name: chat-copilot-webapi
        image: chat-copilot-webapi:latest  # Local image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: Authentication__Type
          value: "None"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        # Note: You'll need to create a Secret for any sensitive environment variables
        # Below is just a placeholder - create a proper Secret for these values
        envFrom:
        - secretRef:
            name: chat-copilot-secret  # This secret needs to be created
---
apiVersion: v1
kind: Service
metadata:
  name: chat-copilot-webapi
spec:
  selector:
    app: chat-copilot-webapi
  ports:
  - port: 3080
    targetPort: 8080
  type: ClusterIP  # Using ClusterIP as we'll access it through the Ingress