apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-copilot-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-copilot-webapi
  template:
    metadata:
      labels:
        app: chat-copilot-webapi
    spec:
      containers:
      - name: chat-copilot-webapi
        image: chat-copilot-webapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: Authentication__Type
          value: "None"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: GOOGLE_PROJECT_ID 
          value: "rag-widget"
        # Don't need to set GOOGLE_APPLICATION_CREDENTIALS as the app uses a default path
        # Instead, mount the secret at the expected path
        volumeMounts:
        - name: gcp-key-volume
          mountPath: "/app/secrets"
          readOnly: true
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-secrets
          items:
          - key: gcp-sa-key.json
            path: gcp-sa-key.json
---
apiVersion: v1
kind: Service
metadata:
  name: chat-copilot-webapi
spec:
  selector:
    app: chat-copilot-webapi
  ports:
  - port: 3080
    targetPort: 8080
  type: ClusterIP