# frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rag-widget-frontend:latest  # Local image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://rag-widget.local/api"  # Use the ingress URL
        - name: AUTH0_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: SESSION_KEY
        - name: AUTH0_BASE_URL
          value: "http://rag-widget.local"
        - name: AUTH0_ISSUER_BASE_URL
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: AUTH0_DOMAIN
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: AUTH0_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP  # Changed to ClusterIP as we'll access through Ingress
  selector:
    app: frontend
  ports:
  - port: 3003
    targetPort: 80