apiVersion: v1
kind: Secret
metadata:
  name: gcp-secrets
type: Opaque
data:
  # Replace these with your actual base64-encoded values
  # You can use: cat rag-widget-1b0f63fa8b77.json | base64 -w 0
  # to generate the base64-encoded service account key
  gcp-sa-key.json: REPLACE_WITH_BASE64_ENCODED_SA_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-config
data:
  GCP_PROJECT_ID: "rag-widget"
  GCP_PUBSUB_TOPIC: "video-processing-queue"
  GCP_STORAGE_BUCKET: "rag-widget-processed-videos"